// Generated by https://quicktype.io

class Peliculas {
  List<Pelicula> items = new List();

  Peliculas();

  Peliculas.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    for (var item in jsonList) {
      final pelicula = new Pelicula.fromJsonMap(item);
      items.add(pelicula); //cramos una lista de objetos pelicula

    }
  }
}

class Pelicula {
  String uniqueId;
  String originalTitle;
  String posterPath;
  bool video;
  double voteAverage;
  String overview;
  String releaseDate;
  String title;
  double popularity;
  bool adult;
  String backdropPath;
  int id;
  List<int> genreIds;
  int voteCount;
  String originalLanguage;

  Pelicula({
    this.originalTitle,
    this.posterPath,
    this.video,
    this.voteAverage,
    this.overview,
    this.releaseDate,
    this.title,
    this.popularity,
    this.adult,
    this.backdropPath,
    this.id,
    this.genreIds,
    this.voteCount,
    this.originalLanguage,
  });

  Pelicula.fromJsonMap(Map<String, dynamic> json) {
    originalTitle = json['original_title'];
    posterPath = json['poster_path'];
    video = json['video'];
    voteAverage = json['vote_average'] / 1;
    overview = json['overview'];
    releaseDate = json['release_date'];
    title = json['title'];
    popularity = json['popularity'] / 1;
    adult = json['adult'];
    backdropPath = json['backdrop_path'];
    id = json['id'];
    genreIds = json['genre_ids'].cast<int>();
    voteCount = json['vote_count'];
    originalLanguage = json['original_language'];
  }

  getPosterPath() {
    if (posterPath == null) {
      return 'https://cdn11.bigcommerce.com/s-hcp6qon/stencil/da04aba0-f23f-0138-05ba-0242ac110012/icons/icon-no-image.svg';
    } else {
      return 'https://image.tmdb.org/t/p/w500/$posterPath';
    }
  }

  getBackgroundImg() {
    if (backdropPath == null) {
      return 'https://cdn11.bigcommerce.com/s-hcp6qon/stencil/da04aba0-f23f-0138-05ba-0242ac110012/icons/icon-no-image.svg';
    } else {
      return 'https://image.tmdb.org/t/p/w500/$backdropPath';
    }
  }
}
